### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by arranloams** [axet/libtorrent#1]
appears to be missing a file:
gomobile bind -o libtorrent.aar github.com/axet/libtorrent results in: 

gomobile: loadExportData failed go install -p=4 -pkgdir=C:\Go\projects\pkg\gomobile/pkg_android_arm -tags="" -gcflags=-shared -ldflags=-shared github.com/axet/libtorrent failed: exit status 2
# github.com/axet/libtorrent
C:\Go\projects\src\github.com\axet\libtorrent\files.go:63: t.PieceBytesCompleted undefined (type *torrent.Torrent has no field or method PieceBytesCompleted)
C:\Go\projects\src\github.com\axet\libtorrent\files.go:64: t.PieceLength undefined (type *torrent.Torrent has no field or method PieceLength, but does have torrent.pieceLength)
C:\Go\projects\src\github.com\axet\libtorrent\files.go:68: t.PieceBytesCompleted undefined (type *torrent.Torrent has no field or method PieceBytesCompleted)
C:\Go\projects\src\github.com\axet\libtorrent\files.go:68: t.PieceLength undefined (type *torrent.Torrent has no field or method PieceLength, but does have torrent.pieceLength)
C:\Go\projects\src\github.com\axet\libtorrent\files.go:68: t.PieceBytesCompleted undefined (type *torrent.Torrent has no field or method PieceBytesCompleted)
C:\Go\projects\src\github.com\axet\libtorrent\files.go:68: t.PieceLength undefined (type *torrent.Torrent has no field or method PieceLength, but does have torrent.pieceLength)
C:\Go\projects\src\github.com\axet\libtorrent\files.go:164: t.GetPendingPieces undefined (type *torrent.Torrent has no field or method GetPendingPieces)
C:\Go\projects\src\github.com\axet\libtorrent\files.go:202: t.UpdatePiecePriorities undefined (type *torrent.Torrent has no field or method UpdatePiecePriorities, but does have torrent.updatePiecePriorities)
C:\Go\projects\src\github.com\axet\libtorrent\files.go:254: t.PieceLength undefined (type *torrent.Torrent has no field or method PieceLength, but does have torrent.pieceLength)
C:\Go\projects\src\github.com\axet\libtorrent\files.go:265: t.PieceBytesCompleted undefined (type *torrent.Torrent has no field or method PieceBytesCompleted)
C:\Go\projects\src\github.com\axet\libtorrent\files.go:265: too many errors

**Comment by axet** [comment]
This library just a concept, not an actual library as you can see in build instructions. It is not suppose to work.
